### ISSUE TITLE
Paper bins cannot be removed from dufflebags or trash piles

### ISSUE THREAD

**Issue by Jamini** [SyzygyStation/Syzygy-Eris#163]
#### Description of issue

Paper bins, when placed or found in dufflebags or trash bins, cannot be removed.

#### Difference between expected and actual behavior

Expected: Drag-clicking the bin to an empty hand would place it in a hand.
Actual behavior: The paper bin is stuck forever until the end of the round.

#### Steps to reproduce 

1. Obtain a dufflebag
2. Obtain a paper bin
3. Put paper bin in dufflebag
4. Flail helplessly as your paper bin is now forever fused with the duffle

#### Length of time in which bug has been known to occur

Unknown. Regular backpacks work fine. It may be related with Eris ground containers (Dufflebags and Trash piles)

#### Client version, Server revision & Game ID

Server revision: master - 
7629e59ecd2a7c09cfe740192510f46c881a8a67

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by ShadzFen** [comment]
You have to drag it onto your character's sprite, not your hand. Whether or not this should be changed has been discussed previously and came to the conclusion that it should remain as is.
