### ISSUE TITLE
Carrion regen breaks things

### ISSUE THREAD

**Issue by Torque4607** [SyzygyStation/Syzygy-Eris#60]
#### Description of issue

The Carrion antagonist regen ability deletes the spider core and spits all implants out of the body. It causes this because it just calls a rejuvenate, which does the same.

#### Difference between expected and actual behavior

Expected that Carrion antag stuff _doesn't_ get vomited out when using an ability

#### Steps to reproduce 

Play Carrion antagonist, get harmed, use regeneration

#### Specific information for locating

Antagonist type: Carrion
Function: Rejuvinate, also accessible through an admin's right-click menu.

#### Length of time in which bug has been known to occur

Unknown, rejuvenate bug has existed for a long time.

#### Client version, Server revision & Game ID

Most recent server revision as of 27-08-2020.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/discordia-space/CEV-Eris/issues)

**Comment by martinlyra** [comment]
PR https://github.com/SyzygyStation/Syzygy-Eris/pull/102 should have fixed this. Feel free to reopen this if the problem still persist.
